### ISSUE TITLE
Error ECONNRESET LTCR Error

### ISSUE THREAD

**Issue by leonid-varygin** [crypti/cryptocurrencies#25]
![Screenshot_1](https://user-images.githubusercontent.com/39562139/138689963-b3934ff0-bed7-4219-b991-ab4004aca4d8.jpg)
Hi. When trying to get data, I see an error like in the screenshot.
How can I fix this?

**Comment by radiovisual** [comment]
I will close this error, since it was so many years ago, but this just looks like your network failed while it was fetching the list of coins. There is not great support for failures or retries when fetching the coin data, so I would just just try again. If you keep finding the same problem, please open a new issue.
